#!/usr/bin/env node

// Standalone `auth.command` helper published as the `paperclip-databricks-oauth-token`
// bin of this package. It is spawned by the run's Codex process (see the
// `[model_providers.databricks.auth]` block generated by
// `buildDatabricksProvidersPayload`) to mint a short-lived OAuth M2M access
// token on demand and on each `refresh_interval_ms`.
//
// Boundary constraint (Requirements 4.4-4.6/4.8): like `checkDatabricksConnectivity`
// in this package, this file MUST NOT import from `server/src/*`. The Databricks
// OAuth token exchange is therefore reimplemented here as a self-contained HTTP
// call rather than reused from `server/src/services/databricks-oauth.ts`.
//
// Contract:
//  - Input: the `DATABRICKS_CREDENTIAL_FILE` env var points at a JSON file
//    `{ host, clientId, clientSecret }` written by the runtime with mode 0600.
//    The `clientSecret` is NEVER accepted via a command-line argument.
//  - Success: writes ONLY the raw `access_token` to stdout, with no trailing
//    newline and no other character before or after it.
//  - Failure (missing/malformed file, non-2xx HTTP, timeout, malformed body):
//    writes a sanitized message to stderr that never contains the
//    `clientSecret`, any access token, or the Databricks response body, and
//    exits with a non-zero code.

import { realpathSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const TOKEN_ENDPOINT_PATH = "/oidc/v1/token";
/** Self-applied request timeout; the run's `auth.timeout_ms` bounds it externally. */
const REQUEST_TIMEOUT_MS = 10_000;
/** Defensive cap on the token response body; OIDC token responses are tiny JSON. */
const MAX_RESPONSE_BYTES = 64 * 1024;

/**
 * An error whose message is already sanitized and safe to print to stderr.
 * Only fixed, generic strings are ever passed here — never a raw credential,
 * token, response body, or an upstream error's own message.
 */
export class HelperError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "HelperError";
  }
}

export interface Credential {
  host: string;
  clientId: string;
  clientSecret: string;
}

/**
 * Reads and validates the credential file referenced by
 * `DATABRICKS_CREDENTIAL_FILE`. The env map is injectable so the helper can be
 * exercised in tests without mutating the ambient `process.env`.
 */
export async function readCredential(
  env: NodeJS.ProcessEnv = process.env,
): Promise<Credential> {
  const filePath = env.DATABRICKS_CREDENTIAL_FILE;
  if (typeof filePath !== "string" || filePath.length === 0) {
    throw new HelperError("DATABRICKS_CREDENTIAL_FILE is not set");
  }

  let raw: string;
  try {
    raw = await readFile(filePath, "utf8");
  } catch {
    // Never echo the underlying fs error: its message can include the file path
    // but, more importantly, we keep failure output uniform and body-free.
    throw new HelperError("Failed to read the Databricks credential file");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    // A JSON parse error message can echo file contents (which hold the
    // clientSecret); never surface it.
    throw new HelperError("Databricks credential file is not valid JSON");
  }

  if (typeof parsed !== "object" || parsed === null) {
    throw new HelperError("Databricks credential file is missing required fields");
  }
  const { host, clientId, clientSecret } = parsed as Record<string, unknown>;
  if (
    typeof host !== "string" ||
    host.length === 0 ||
    typeof clientId !== "string" ||
    clientId.length === 0 ||
    typeof clientSecret !== "string" ||
    clientSecret.length === 0
  ) {
    throw new HelperError("Databricks credential file is missing required fields");
  }

  return { host, clientId, clientSecret };
}

/**
 * Trades the service-principal `clientId`/`clientSecret` for a workspace access
 * token via `POST {host}/oidc/v1/token` with `grant_type=client_credentials`
 * and HTTP Basic auth. Bounded by a self-applied timeout, with no implicit
 * retry. Never surfaces the secret, the token, or the response body on failure.
 */
export async function exchangeToken(credential: Credential): Promise<string> {
  let url: URL;
  try {
    url = new URL(TOKEN_ENDPOINT_PATH, credential.host);
  } catch {
    throw new HelperError("Databricks credential file has an invalid host");
  }

  const basic = Buffer.from(`${credential.clientId}:${credential.clientSecret}`).toString(
    "base64",
  );

  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Basic ${basic}`,
        "Content-Type": "application/x-www-form-urlencoded",
        Accept: "application/json",
      },
      body: "grant_type=client_credentials",
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      redirect: "error",
    });
  } catch (error) {
    const isTimeout =
      error instanceof Error &&
      (error.name === "TimeoutError" || error.name === "AbortError");
    throw new HelperError(
      isTimeout
        ? "Databricks token request timed out"
        : "Databricks token endpoint could not be reached",
    );
  }

  if (!response.ok) {
    // Discard the body without ever inspecting or surfacing it: OAuth error
    // bodies can echo request context. The status code alone is safe to report.
    await response.body?.cancel().catch(() => {});
    throw new HelperError(`Databricks token endpoint returned HTTP ${response.status}`);
  }

  const body = await readBoundedJson(response);
  const token = body.access_token;
  if (typeof token !== "string" || token.length === 0) {
    throw new HelperError("Databricks token response did not contain an access token");
  }
  return token;
}

interface TokenResponseBody {
  access_token?: unknown;
}

/** Reads the response body up to a bounded size, then parses it as JSON. */
async function readBoundedJson(response: Response): Promise<TokenResponseBody> {
  if (!response.body) {
    throw new HelperError("Databricks token response did not contain an access token");
  }
  const reader = response.body.getReader();
  const parts: Uint8Array[] = [];
  let bytes = 0;
  try {
    for (;;) {
      const part = await reader.read();
      if (part.done) break;
      bytes += part.value.length;
      if (bytes > MAX_RESPONSE_BYTES) {
        throw new HelperError("Databricks token response exceeded the processing limit");
      }
      parts.push(part.value);
    }
  } finally {
    await reader.cancel().catch(() => {});
  }

  const text = Buffer.concat(parts).toString("utf8");
  try {
    return JSON.parse(text) as TokenResponseBody;
  } catch {
    // Never echo the malformed body.
    throw new HelperError("Databricks returned a malformed token response");
  }
}

/** Writes `data` to stdout and resolves once it has been flushed. */
function writeStdout(data: string): Promise<void> {
  return new Promise((resolve, reject) => {
    process.stdout.write(data, (error) => (error ? reject(error) : resolve()));
  });
}

/** Injectable side-effect surfaces so the CLI can be unit tested without a
 * subprocess and without mutating the ambient process/streams. */
export interface CliIo {
  /** Defaults to a stdout write. */
  stdout?: (data: string) => Promise<void> | void;
  /** Defaults to a stderr write. */
  stderr?: (data: string) => void;
  /** Defaults to `process.env`. */
  env?: NodeJS.ProcessEnv;
}

/**
 * Runs the full helper: read the credential file, exchange it for an access
 * token, and write ONLY the token to stdout on success. On any failure it
 * writes a sanitized (secret/token/body-free) message to stderr and resolves
 * with a non-zero exit code. It never throws.
 */
export async function runCli(io: CliIo = {}): Promise<number> {
  const stdout = io.stdout ?? writeStdout;
  const stderr = io.stderr ?? ((data: string) => void process.stderr.write(data));
  const env = io.env ?? process.env;
  try {
    const credential = await readCredential(env);
    const token = await exchangeToken(credential);
    // Emit ONLY the token, with no trailing newline or any other character.
    await stdout(token);
    return 0;
  } catch (error) {
    const message =
      error instanceof HelperError ? error.message : "Databricks token request failed";
    stderr(`${message}\n`);
    return 1;
  }
}

/** True only when this module is executed directly as the published bin, not
 * when it is imported (e.g. by the test runner). */
function isInvokedAsBin(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (isInvokedAsBin()) {
  void runCli().then((code) => {
    process.exitCode = code;
  });
}
